# Generated by Django 5.1.4 on 2024-12-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_utilisateur_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='profile_picture_path',
            field=models.FileField(blank=True, null=True, upload_to='Static/Profile_pictures/'),
        ),
    ]
