# Generated by Django 5.1.4 on 2024-12-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_utilisateur_profile_picture_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdataset',
            name='selectedTargetColumn',
            field=models.CharField(default='target', max_length=255),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='profile_picture_path',
            field=models.FileField(blank=True, null=True, upload_to='Profile_pictures/'),
        ),
    ]
