# Generated by Django 5.1.4 on 2024-12-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rawdataset_selectedtargetcolumn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdataset',
            name='datasetCostumName',
            field=models.CharField(blank=True, default='DataSetFile', max_length=100, null=True),
        ),
    ]
