# Generated by Django 5.0.6 on 2024-12-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rawdataset_datasetcostumname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawdataset',
            old_name='selectedTargetColumn',
            new_name='TargetColumn',
        ),
        migrations.AddField(
            model_name='preprocesseddataset',
            name='preprocessedCostumName',
            field=models.CharField(blank=True, default='PreprocessedDataSetFile', max_length=100, null=True),
        ),
    ]
