# Generated by Django 5.1.4 on 2024-12-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_selectedtargetcolumn_rawdataset_targetcolumn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdataset',
            name='TargetColumn',
            field=models.CharField(blank=True, default='target', max_length=255, null=True),
        ),
    ]
