# Generated by Django 5.1.4 on 2024-12-19 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_rawdataset_targetcolumn'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataVisualization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visualization_name', models.CharField(default='Visualization', max_length=100)),
                ('graph_type', models.CharField(max_length=50)),
                ('graph_file', models.FileField(blank=True, null=True, upload_to='data_visualizations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rawdataset')),
                ('dataset_processed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.preprocesseddataset')),
            ],
        ),
    ]
