# Generated by Django 5.1.4 on 2024-12-19 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_datavisualization'),
        ('app', '0008_result_mcc_result_precision_result_r2_score_and_more'),
    ]

    operations = [
    ]
