# Generated by Django 5.1.4 on 2024-12-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_merge_20241219_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprocesseddataset',
            name='preprocessedCostumName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
