# Generated by Django 5.1.4 on 2024-12-22 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_result_mcc_remove_result_accuracy_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataGraph',
        ),
    ]
